name = "Cryptics"
uuid = "0fbdecee-01fc-11e9-134a-45d008bceca4"
authors = ["Robin Deits <robin.deits@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
